image: empty_map.pgm
resolution: 0.05  # meters per pixel
origin: [0.0, 0.0, 0.0]  # bottom-left corner of the map
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0  # 0 indicates white as free, black as obstacles
